# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5174cdf7dfd564ec15662ea9c237b972"
name = "checkout-update"
handle = "checkout-update-5"
application_url = "https://present-there-limitation-decided.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://present-there-limitation-decided.trycloudflare.com/auth/callback", "https://present-there-limitation-decided.trycloudflare.com/auth/shopify/callback", "https://present-there-limitation-decided.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
