# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "25fcded3cbdfee6e44a79ab0b1c299a1"
name = "checkout-update"
handle = "checkout-update-5"
application_url = "https://applying-season-figured-integrate.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://applying-season-figured-integrate.trycloudflare.com/auth/callback", "https://applying-season-figured-integrate.trycloudflare.com/auth/shopify/callback", "https://applying-season-figured-integrate.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
