# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "46033d79fed020a5f5a158634541af7a"
name = "post-purchase-offers"
handle = "post-purchase-offers-6"
application_url = "https://tee-fe-salt-strings.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://tee-fe-salt-strings.trycloudflare.com/auth/callback", "https://tee-fe-salt-strings.trycloudflare.com/auth/shopify/callback", "https://tee-fe-salt-strings.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
